try {
  person;
  let person = "Foluso";
} catch (error) {
  console.log(error);
}
